BUILTINS_INFO = {'printInt': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'printInt',
        'ListArg': [{'Name': 'x', 'LatteType': {'TypeName': 'int', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1},
            'StartPos': -1, 'EndPos': -1}],
        'Body': [], 'LatteType': {'TypeName': 'void', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}},
    'printString': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'printString',
        'ListArg': [{'Name': 'x', 'LatteType': {'TypeName': 'string', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1},
            'StartPos': -1, 'EndPos': -1}],
        'Body': [], 'LatteType': {'TypeName': 'void', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}},
    'printBool': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'printBool',
        'ListArg': [{'Name': 'x', 'LatteType': {'TypeName': 'boolean', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1},
            'StartPos': -1, 'EndPos': -1}],
        'Body': [], 'LatteType': {'TypeName': 'void', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}},
    'readInt': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'readInt',
        'ListArg': [],'Body': [], 'LatteType': {'TypeName': 'int', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}},
            'readString': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'readString',
        'ListArg': [],'Body': [], 'LatteType': {'TypeName': 'string', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}},
    'readBool': {'Type': 'FunDecl', 'LineNo': -1, 'Name': 'readBool',
        'ListArg': [],'Body': [], 'LatteType': {'TypeName': 'boolean', 'LineNo': -1, 'StartPos': -1, 'EndPos': -1}}}


